swagger: '2.0'
info:
  title: 3scale Zync REST Adapter API
  version: '2.11'
  description: >-
    The API expected by Zync when using a third-party identity provider. This is for all identity
    providers other than Red Hat Single-Sign On.
paths:
  /.well-known/openid-configuration:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Successful response with IdP configuration
          schema:
            $ref: '#/definitions/OpenIdConnectConfiguration'
      operationId: read-openid-configuration
      summary: Read OpenID Configuration
      description: >-
        [Red Hat 3scale API Management documentation for Using OAuth2
        authentication](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/administering_the_api_gateway/openid-connect#using_oauth2_authentication)
  '/clients/{client_id}':
    put:
      consumes:
        - application/json
      parameters:
        -
          name: body
          schema:
            $ref: '#/definitions/ClientUpdatePayload'
          in: body
          required: true
        -
          name: client_id
          description: The client ID to create or update
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful update
      operationId: create-or-update-client
      summary: Create or Update Client
      description: >-
        Create a new client, or update an existing client.


        [Red Hat 3scale API Management documentation for Creating, updating and deleting
        clients](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/administering_the_api_gateway/openid-connect#creating_updating_and_deleting_clients)
    delete:
      parameters:
        -
          name: client_id
          description: The client ID to delete
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful deletion
      operationId: delete-client
      summary: Delete Client
      description: >-
        Delete an existing client from the identity provider


        [Red Hat 3scale API Management documentation for Creating, updating and deleting
        clients](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/administering_the_api_gateway/openid-connect#creating_updating_and_deleting_clients)
definitions:
  ClientUpdatePayload:
    title: ClientUpdatePayload
    description: >-
      Payload to describe the desired state for a client ID in the Identity Provider


      [Red Hat 3scale API Management documentation for
      Payload](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/administering_the_api_gateway/openid-connect#payload)
    required:
      - client_id
      - client_secret
      - client_name
      - redirect_uris
      - grant_types
    type: object
    properties:
      client_id:
        type: string
      client_secret:
        type: string
      client_name:
        type: string
      redirect_uris:
        type: array
        items:
          type: string
      grant_types:
        type: array
        items:
          $ref: '#/definitions/GrantTypeEnum'
    example:
      client_id: ee305610
      client_secret: ac0e42db426b4377096c6590e2b06aed
      client_name: oidc-app
      redirect_uris:
        - 'https://example.com'
      grant_types:
        - client_credentials
        - password
  GrantTypeEnum:
    description: An enum of the available grant types recognized by Zync
    enum:
      - authorization_code
      - implicit
      - client_credentials
      - password
    type: string
  OpenIdConnectConfiguration:
    title: OpenIdConnectConfiguration
    description: >-
      The conventional JSON object that describes endpoints and options for an OpenID Connect identity
      provider
    required:
      - issuer
      - token_endpoint
    type: object
    properties:
      issuer:
        type: string
      authorization_endpoint:
        type: string
      token_endpoint:
        type: string
      introspection_endpoint:
        type: string
      userinfo_endpoint:
        type: string
      end_session_endpoint:
        type: string
      jwks_uri:
        type: string
      check_session_iframe:
        type: string
      grant_types_supported:
        type: array
        items:
          type: string
      response_types_supported:
        type: array
        items:
          type: string
      subject_types_supported:
        type: array
        items:
          type: string
      id_token_signing_alg_values_supported:
        type: array
        items:
          type: string
      id_token_encryption_alg_values_supported:
        type: array
        items:
          type: string
      id_token_encryption_enc_values_supported:
        type: array
        items:
          type: string
      userinfo_signing_alg_values_supported:
        type: array
        items:
          type: string
      request_object_signing_alg_values_supported:
        type: array
        items:
          type: string
      request_object_encryption_alg_values_supported:
        type: array
        items:
          type: string
      request_object_encryption_enc_values_supported:
        type: array
        items:
          type: string
      response_modes_supported:
        type: array
        items:
          type: string
      registration_endpoint:
        type: string
      token_endpoint_auth_methods_supported:
        type: array
        items:
          type: string
      token_endpoint_auth_signing_alg_values_supported:
        type: array
        items:
          type: string
      introspection_endpoint_auth_methods_supported:
        type: array
        items:
          type: string
      introspection_endpoint_auth_signing_alg_values_supported:
        type: array
        items:
          type: string
      authorization_signing_alg_values_supported:
        type: array
        items:
          type: string
      authorization_encryption_alg_values_supported:
        type: array
        items:
          type: string
      authorization_encryption_enc_values_supported:
        type: array
        items:
          type: string
      claims_supported:
        type: array
        items:
          type: string
      claim_types_supported:
        type: array
        items:
          type: string
      claims_parameter_supported:
        type: boolean
      scopes_supported:
        type: array
        items:
          type: string
      request_parameter_supported:
        type: boolean
      request_uri_parameter_supported:
        type: boolean
      require_request_uri_registration:
        type: boolean
      code_challenge_methods_supported:
        type: array
        items:
          type: string
      tls_client_certificate_bound_access_tokens:
        type: boolean
      revocation_endpoint:
        type: string
      revocation_endpoint_auth_methods_supported:
        type: array
        items:
          type: string
      revocation_endpoint_auth_signing_alg_values_supported:
        type: array
        items:
          type: string
      backchannel_logout_supported:
        type: boolean
      backchannel_logout_session_supported:
        type: boolean
      device_authorization_endpoint:
        type: string
      backchannel_token_delivery_modes_supported:
        type: array
        items:
          type: string
      backchannel_authentication_endpoint:
        type: string
      backchannel_authentication_request_signing_alg_values_supported:
        type: array
        items:
          type: string
      require_pushed_authorization_requests:
        type: boolean
      pushed_authorization_request_endpoint:
        type: string
    additionalProperties: true
    example:
      issuer: 'https://idp.example.com/'
      authorization_endpoint: 'https://idp.example.com//protocol/openid-connect/auth'
      token_endpoint: 'https://idp.example.com//protocol/openid-connect/token'
      introspection_endpoint: 'https://idp.example.com//protocol/openid-connect/token/introspect'
      userinfo_endpoint: 'https://idp.example.com//protocol/openid-connect/userinfo'
      end_session_endpoint: 'https://idp.example.com//protocol/openid-connect/logout'
      jwks_uri: 'https://idp.example.com//protocol/openid-connect/certs'
      check_session_iframe: 'https://idp.example.com//protocol/openid-connect/login-status-iframe.html'
      grant_types_supported:
        - authorization_code
        - implicit
        - refresh_token
        - password
        - client_credentials
        - 'urn:ietf:params:oauth:grant-type:device_code'
        - 'urn:openid:params:grant-type:ciba'
      response_types_supported:
        - code
        - none
        - id_token
        - token
        - id_token token
        - code id_token
        - code token
        - code id_token token
      subject_types_supported:
        - public
        - pairwise
      id_token_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
      id_token_encryption_alg_values_supported:
        - RSA-OAEP
        - RSA-OAEP-256
        - RSA1_5
      id_token_encryption_enc_values_supported:
        - A256GCM
        - A192GCM
        - A128GCM
        - A128CBC-HS256
        - A192CBC-HS384
        - A256CBC-HS512
      userinfo_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
        - none
      request_object_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
        - none
      request_object_encryption_alg_values_supported:
        - RSA-OAEP
        - RSA-OAEP-256
        - RSA1_5
      request_object_encryption_enc_values_supported:
        - A256GCM
        - A192GCM
        - A128GCM
        - A128CBC-HS256
        - A192CBC-HS384
        - A256CBC-HS512
      response_modes_supported:
        - query
        - fragment
        - form_post
        - query.jwt
        - fragment.jwt
        - form_post.jwt
        - jwt
      registration_endpoint: 'https://idp.example.com//clients-registrations/openid-connect'
      token_endpoint_auth_methods_supported:
        - private_key_jwt
        - client_secret_basic
        - client_secret_post
        - tls_client_auth
        - client_secret_jwt
      token_endpoint_auth_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
      introspection_endpoint_auth_methods_supported:
        - private_key_jwt
        - client_secret_basic
        - client_secret_post
        - tls_client_auth
        - client_secret_jwt
      introspection_endpoint_auth_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
      authorization_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
      authorization_encryption_alg_values_supported:
        - RSA-OAEP
        - RSA-OAEP-256
        - RSA1_5
      authorization_encryption_enc_values_supported:
        - A256GCM
        - A192GCM
        - A128GCM
        - A128CBC-HS256
        - A192CBC-HS384
        - A256CBC-HS512
      claims_supported:
        - aud
        - sub
        - iss
        - auth_time
        - name
        - given_name
        - family_name
        - preferred_username
        - email
        - acr
      claim_types_supported:
        - normal
      claims_parameter_supported: true
      scopes_supported:
        - openid
        - offline_access
        - profile
        - web-origins
        - microprofile-jwt
        - email
        - phone
        - roles
        - address
      request_parameter_supported: true
      request_uri_parameter_supported: true
      require_request_uri_registration: true
      code_challenge_methods_supported:
        - plain
        - S256
      tls_client_certificate_bound_access_tokens: true
      revocation_endpoint: 'https://idp.example.com//protocol/openid-connect/revoke'
      revocation_endpoint_auth_methods_supported:
        - private_key_jwt
        - client_secret_basic
        - client_secret_post
        - tls_client_auth
        - client_secret_jwt
      revocation_endpoint_auth_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - HS256
        - HS512
        - ES256
        - RS256
        - HS384
        - ES512
        - PS256
        - PS512
        - RS512
      backchannel_logout_supported: true
      backchannel_logout_session_supported: true
      device_authorization_endpoint: 'https://idp.example.com//protocol/openid-connect/auth/device'
      backchannel_token_delivery_modes_supported:
        - poll
        - ping
      backchannel_authentication_endpoint: 'https://idp.example.com//protocol/openid-connect/ext/ciba/auth'
      backchannel_authentication_request_signing_alg_values_supported:
        - PS384
        - ES384
        - RS384
        - ES256
        - RS256
        - ES512
        - PS256
        - PS512
        - RS512
      require_pushed_authorization_requests: false
      pushed_authorization_request_endpoint: 'https://idp.example.com//protocol/openid-connect/ext/par/request'
