apiVersion: v1
kind: Secret
metadata:
  name: okta-credentials
  labels:
    app: 3scale-okta-rest-adapter
    application: 3scale-okta-rest-adapter
type: Opaque
stringData:
  issuer: https://dev-39092990.okta.com/oauth2/default
  org-url: https://dev-39092990.okta.com
  access-token: 00eG0riLX8uEa5fsVNJKoNK8nHG_k5AjAOGavzwzyk
